# Generated by Django 4.2.7 on 2025-09-20 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medic_card", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_question_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Текущий вопрос (индекс)"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Завершен"),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начат"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершен"
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Правильных ответов"
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего вопросов"
                    ),
                ),
                (
                    "time_spent",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Время выполнения"
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medic_card.ticket",
                        verbose_name="Билет",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс билета",
                "verbose_name_plural": "Прогресс билетов",
                "unique_together": {("user", "ticket")},
            },
        ),
    ]
