# Generated by Django 4.2.7 on 2025-09-20 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medic_card", "0002_ticketprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="is_temporary",
            field=models.BooleanField(default=False, verbose_name="Временный билет"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="original_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="medic_card.ticket",
                verbose_name="Оригинальный билет",
            ),
        ),
    ]
