# Generated by Django 4.2.7 on 2025-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medic_card", "0004_favorites"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketprogress",
            name="question_order",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Порядок вопросов (ID)"
            ),
        ),
    ]
