# Generated by Django 4.2.7 on 2025-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medic_card", "0005_ticketprogress_question_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="theme",
        ),
        migrations.AddField(
            model_name="ticket",
            name="themes",
            field=models.ManyToManyField(
                related_name="tickets", to="medic_card.theme", verbose_name="Темы"
            ),
        ),
    ]
