# Generated by Django 4.2.7 on 2025-11-04 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("medic_card", "0006_remove_ticket_theme_ticket_themes"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="original_question",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_copies",
                to="medic_card.question",
                verbose_name="Оригинальный вопрос",
            ),
        ),
    ]
