# Generated by Django 4.2.7 on 2025-09-19 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password_hint",
                    models.CharField(
                        blank=True,
                        help_text="Подсказка для восстановления пароля (будет показана после 3 неудачных попыток входа)",
                        max_length=200,
                    ),
                ),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("last_failed_attempt", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
