# Generated by Django 4.2.7 on 2025-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medic_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="correct_answers",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Правильных ответов"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_activity",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mistakes_made",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Совершено ошибок"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tickets_solved",
            field=models.PositiveIntegerField(default=0, verbose_name="Решено билетов"),
        ),
    ]
